### ISSUE TITLE
eval error

### ISSUE THREAD

**Issue by Lovemyse1f** [krishanrana/multiplicative_controller_fusion#1]
hi, when i run mcf_traing script, one error occured.
 agent_loc = [ nan nan],
/pytorch/torch/csrc/utils/tensor_numpy.cpp:141: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program.
Traceback (most recent call last):
  File "MCF_Training.py", line 490, in <module>
    evaluate_agent(i)
  File "MCF_Training.py", line 220, in evaluate_agent
    o, r, d, _ = env.step(act)
  File "/home/test/src/multiplicative_controller_fusion-master/PointGoalNavigationEnv.py", line 348, in step
    dist = self._obs()[-2]
  File "/home/test/src/multiplicative_controller_fusion-master/PointGoalNavigationEnv.py", line 409, in _obs
    self.world.RayCast(callback, start, end)
AssertionError: r.LengthSquared() > 0.0f

and another questions:
 why each step uses 3  _laser_rays?
 
hoping your answer,
 thank you,sir

**Comment by Lovemyse1f** [comment]
make num_agents >1 .
